title: "Onepage Documentation"
nav-header: "Onepage Documentation"
nav-description: "Theme by Harry Iliffe"

colors:
  - name: "primary" # Change these colours! Warning: "Primary" changes all the buttons, link text, etc
    color: "#a9c931"
  - name: "secondary"
    color: "#6c757d"
  - name: "customcolor1" # You can add you own colours and everything
    color: "#fc4a1a"


baseurl: "/OnepageDocumentationTheme" #this is the name of your repository and is used to make your urls work. eg for harryiliffe.github.io/open-design-2018/ the baseurl would be "/open-design-2018"

# Probably dont edit this stuff!
include: ["_pages"]
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      hidden: false
